### PR TITLE
Fix extra parenthesis in code links

### PR DESCRIPTION
**Pull request by neoranga55**
This fixes the links markup to java code

### CODE REVIEW

**Comment by neoranga55** [comment]
I signed it!

**Comment by keyboardsurfer** [comment]
Please make sure to select `Any other Google project` when signing the CLA.

**Comment by neoranga55** [comment]
I signed it! Now with the 'Any other Google project'

**Comment by JoseAlcerreca** [comment]
No wonder why the link checker didn't complain, thanks!

**Pull request merged**
