### PR TITLE
Fix broken link to documentation

### PR DESCRIPTION
**Pull request by MichaelEvans**

### CODE REVIEW

**Comment by JoseAlcerreca** [comment]
Thanks for the first PR :+1: We didn't have googlebot set up yet. Testing if this comment triggers it...

**Comment by keyboardsurfer** [comment]
Thanks for your pull request.  It looks like this may be your first contribution to a Google open source project, in which case you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit <https://cla.developers.google.com/> to sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify.  Thanks.

---

- If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
- If you signed the CLA as a corporation, please let us know the company's name.

**Comment by MichaelEvans** [comment]
Interesting, I have signed the CLA - it shows up when I check the data. Any ideas?

**Comment by JoseAlcerreca** [comment]
Thanks!

**Pull request merged**
